# Set the maximum line length to 100.
line-length = 100

[lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
extend-select = ["E501", "ANN"]

# Exclude a variety of commonly ignored directories.
exclude = []


[lint.pydocstyle]
convention = "google"